### ISSUE TITLE
Form-Card

### ISSUE THREAD

**Issue by Lu202** [Lu202/capstone-project#2]

**Comment by Lu202** [comment]
**App for animal shelter
**I need  animals pictures
**I need  to display cards

Description
design or text
- [ ] create a card-profile for animals
- [ ] Input field with name
- [ ] Selection box between cat or dog
- [ ] Input field age of the animal
- [ ] Input field health status
- [ ] Input field character
- [ ] Input animal feed
- [ ] image box for uploading images
- [ ] Button to send all information to the next page and create a Profile-Card for animals
- [ ] Back Button navigate to the start page

Acceptance Criteria
- [ ] each Each entry should be visually separated
- [ ] All available entries should be displayed

 ...
Tasks
- [ ] Create a new branch " display-form"
- [ ] Create the data structure to hold the form details
- [ ] Create a component to render the form
- [ ] The component receives the array via props
- [ ] Add a test to check if all given entries are rendered
- [ ] Add Component to the app
- [ ] Add to storybook
- [ ] Add basic styling


Complexity
M

**Comment by mbosselmann** [comment]
Hi Luljana,
good start of your user story, but there are some aspects of your user story that you should work on:

**In general**
- There exists a basic template with subtitles for user stories that you should use. See the example user stories that were discussed in your course. 
- This template also shows how to styles this file to highlight the structure of each user story section

**Value proposition**
- I identified this part as your value proposition:
```
**App for animal shelter
**I need animals pictures
**I need to display cards
```
- `**App for animal shelter` You don't need to explain this in your user story
- `**I need animals pictures` & `**I need to display cards` won't fulfill the idea of a value proposition: To describe from a user perspective what feature is needed and why
- I think that animal pictures is something that will be displayed in your card, therefore I would suggest to write your value proposition like the following example:

**As a** user
**I want to** see information about an animal I may want to adopt
**to be able to** to make sure that the needs of the animal match what I can provide

**Description**
- I identified this part as the description part:
```
Description
design or text
```
- You need to add your wireframes here that show the card that you want to implement (see example user stories that you discussed in your course)

**Acceptance criteria**
- I think there exists a huge block of acceptance criteria above the heading that should be added as acceptance criteria. Maybe your formatting went wrong here. 🤔 
- I like that these acceptance criteria are very detailed. 👍 I think you could work with indentation here to show that all criteria below the first one should be implemented to finish the first criterion
- `...` above `Tasks` are not needed? 🤔 

**Tasks**
- I like your tasks! 👍 

**Complexity**
- I think that is a good rating for this user story. 👍 

I hope my remarks are understandable. Feel free to ask me if you have further questions! :)

**Comment by PReichetanz** [comment]
Hi Luljana,

looks good, I just have some issues to consider:

## Value proposition
I would slightly rephrase the last part of the value proposition because when submitting the form, you won't directly "share information about animals with my colleagues", but you will store them in your app. Sharing is another step you will do in the future.

## Acceptance criteria
- Where is the image box for uploading images in your design? (Besides, I would outsource the image upload to another story since it is a little bit complicated to work with cloudinary).
- To be clear, you could add an image to show the next page / profile card the user enters / sees after hitting the submit button.
- I don't see the back button in your design.
- Are the input fields required? What happens if I do not fill them before submitting?

## Tasks
" The component receives the array via props" - Which component receives which array via which props?
