### ISSUE TITLE
Edit and Delete Button

### ISSUE THREAD

**Issue by Lu202** [Lu202/capstone-project#5]
# Value Proposition

**Shelter app to share the animals
**Need to edit and delete the profile
**to be able to update the app if something to changes

# Description

Scribble / design or text
two Buttons Delete and Edit 

# Acceptance Criteria

- [ ]  A button to delete the product is displayed, labeled "delete"
- [ ]  A button to edit the product is displayed, labeled "edit"
- [ ]  After clicking the delete Button the product disappears
- [ ]  Edit Button turns in to a save Button
- [ ] After clicking the save Button my changes are updated

# Tasks

(for developers team)

- [ ] Add a new branch "create-delete-and-edit-button"
- [ ] Add Delete and Put CRUD Method to [id].js
- [ ] Add a ProductEditMode function to Product Component

# Complexity
M

**Comment by PReichetanz** [comment]
Hello Luljana,
nice work, but please separate this story into two, for delete and edit, respectively.

When doing so, add an image where the buttons are displayed and located on the screen.
