### ISSUE TITLE
First input field

### ISSUE THREAD

**Issue by Lu202** [Lu202/capstone-project#8]
**App for animal shelter
**I need animals pictures
**I need to display cards
**I need buttons

# Description

Scribble / design or text

# Acceptance Criteria

- [ ] create a card-profile for animals
- [ ]  Input field with name
- [ ] Selection box between cat or dog
- [ ] Input field age of the animal
- [ ] Input field health status
- [ ]  Input field character
- [ ] Input animal feed
- [ ] image box for uploading images
- [ ]  Button to send all information to the next page and create a Profile-Card for animals
- [ ] Back Button navigate to the start page

# Tasks

(for developers team)

- [ ] first create one input field
- [ ] write name example
- [ ] this entries should be displayed

# Complexity
s

**Comment by mbosselmann** [comment]
Hi Luljana, 
I like your user story! 👍 Here are my remarks:

1. `Scribble / design or text` this part can be removed
2. You could be more descriptive in your acceptance criteria. For example:
  - a list with four cards
  - what information will be displayed?
  - the name of the dog will be displayed
  - what will be displayed in this image?
3. In your tasks are some points missing. Check your other user story to see what tasks should be also included in this user story like `create a new branch`, `Add storybook`, `Add test` etc.
