### ISSUE TITLE
Button submit

### ISSUE THREAD

**Issue by Lu202** [Lu202/capstone-project#9]
**App for animal shelter
**I need to display cards
**I need buttons 
**submit, start

# Description

Scribble / design or text

# Acceptance Criteria

- [x] create a card-profile for animals
- [x]  Input field with name
- [x] Input field age of the animal
- [x] Input field health status
- [x]  Input field character
- [x] Input animal feed
- [x]  Button to send all information to the next page and create a Profile-Card for animals

# Tasks

(for developers team)

- [x] enter an entry with the submit button
- [x] then this entries should be displayed 
# Complexity
s
